#! /usr/bin/env python
# -*- coding: utf-8 -*-

"""
@version: ??
@author: li
@file: features.py
@time: 2019/11/11 1:34 下午
"""

uqer_features = [
    'AccountsPayablesTDays', 'AccountsPayablesTRate', 'AdminiExpenseRate', 'ARTDays',
    'ARTRate', 'ASSI', 'BLEV', 'BondsPayableToAsset', 'CashRateOfSales', 'CashToCurrentLiability',
    'CMRA', 'CTOP', 'CTP5', 'CurrentAssetsRatio', 'CurrentAssetsTRate', 'CurrentRatio', 'DAVOL10',
    'DAVOL20', 'DAVOL5', 'DDNBT', 'DDNCR', 'DDNSR', 'DebtEquityRatio', 'DebtsAssetRatio', 'DHILO',
    'DilutedEPS', 'DVRAT', 'EBITToTOR', 'EGRO', 'EMA10', 'EMA120', 'EMA20', 'EMA5', 'EMA60', 'EPS',
    'EquityFixedAssetRatio', 'EquityToAsset', 'EquityTRate', 'ETOP', 'ETP5', 'FinancialExpenseRate',
    'FinancingCashGrowRate', 'FixAssetRatio', 'FixedAssetsTRate', 'GrossIncomeRatio', 'HBETA',
    'HSIGMA', 'IntangibleAssetRatio', 'InventoryTDays', 'InventoryTRate', 'InvestCashGrowRate',
    'LCAP', 'LFLO', 'LongDebtToAsset', 'LongDebtToWorkingCapital', 'LongTermDebtToAsset',
    'MA10', 'MA120', 'MA20', 'MA5', 'MA60', 'MAWVAD', 'MFI', 'MLEV', 'NetAssetGrowRate',
    'NetProfitGrowRate', 'NetProfitRatio', 'NOCFToOperatingNI', 'NonCurrentAssetsRatio',
    'NPParentCompanyGrowRate', 'NPToTOR', 'OperatingExpenseRate', 'OperatingProfitGrowRate',
    'OperatingProfitRatio', 'OperatingProfitToTOR', 'OperatingRevenueGrowRate', 'OperCashGrowRate',
    'OperCashInToCurrentLiability', 'PB','PCF', 'PE','PS','PSY', 'QuickRatio', 'REVS10',
    'REVS20', 'REVS5', 'ROA','ROA5', 'ROE', 'ROE5', 'RSI', 'RSTR12', 'RSTR24', 'SalesCostRatio',
    'SaleServiceCashToOR' , 'SUE', 'TaxRatio', 'TOBT', 'TotalAssetGrowRate', 'TotalAssetsTRate',
    'TotalProfitCostRatio', 'TotalProfitGrowRate', 'VOL10', 'VOL120', 'VOL20', 'VOL240', 'VOL5',
    'VOL60', 'WVAD', 'REC', 'DAREC', 'GREC', 'FY12P', 'DAREV', 'GREV', 'SFY12P', 'DASREV', 'GSREV',
    'FEARNG', 'FSALESG', 'TA2EV', 'CFO2EV', 'ACCA', 'DEGM', 'SUOI', 'EARNMOM', 'FiftyTwoWeekHigh',
    'Volatility', 'Skewness', 'ILLIQUIDITY', 'BackwardADJ', 'MACD', 'ADTM', 'ATR14', 'ATR6', 'BIAS10',
    'BIAS20', 'BIAS5', 'BIAS60', 'BollDown', 'BollUp', 'CCI10', 'CCI20', 'CCI5', 'CCI88', 'KDJ_K', 'KDJ_D',
    'KDJ_J', 'ROC6', 'ROC20', 'SBM', 'STM', 'UpRVI', 'DownRVI', 'RVI', 'SRMI', 'ChandeSD', 'ChandeSU',
    'CMO', 'DBCD', 'ARC', 'OBV', 'OBV6', 'OBV20', 'TVMA20', 'TVMA6', 'TVSTD20', 'TVSTD6', 'VDEA', 'VDIFF',
    'VEMA10', 'VEMA12', 'VEMA26', 'VEMA5', 'VMACD', 'VR', 'VROC12', 'VROC6', 'VSTD10', 'VSTD20', 'KlingerOscillator' ,
    'MoneyFlow20', 'AD', 'AD20', 'AD6','CoppockCurve','ASI', 'ChaikinOscillator', 'ChaikinVolatility',
    'EMV14', 'EMV6', 'plusDI', 'minusDI', 'ADX', 'ADXR', 'Aroon', 'AroonDown', 'AroonUp', 'DEA', 'DIFF', 'DDI', 'DIZ',
    'DIF', 'MTM', 'MTMMA', 'PVT', 'PVT6', 'PVT12', 'TRIX5', 'TRIX10', 'UOS', 'MA10RegressCoeff12', 'MA10RegressCoeff6',
    'PLRC6', 'PLRC12', 'SwingIndex', 'Ulcer10', 'Ulcer5', 'Hurst', 'ACD6', 'ACD20', 'EMA12', 'EMA26', 'APBMA',
    'BBI', 'BBIC', 'TEMA10', 'TEMA5', 'MA10Close', 'AR', 'BR','ARBR', 'CR20', 'MassIndex', 'BearPower', 'BullPower',
    'Elder', 'NVI', 'PVI', 'RC12', 'RC24', 'JDQS20', 'Variance20', 'Variance60', 'Variance120', 'Kurtosis20',
    'Kurtosis60', 'Kurtosis120', 'Alpha20', 'Alpha60', 'Alpha120', 'Beta20', 'Beta60', 'Beta120', 'SharpeRatio20',
    'SharpeRatio60', 'SharpeRatio120', 'TreynorRatio20', 'TreynorRatio60', 'TreynorRatio120', 'InformationRatio20',
    'InformationRatio60', 'InformationRatio120', 'GainVariance20', 'GainVariance60', 'GainVariance120', 'LossVariance20',
    'LossVariance60', 'LossVariance120', 'GainLossVarianceRatio20', 'GainLossVarianceRatio60', 'GainLossVarianceRatio120',
    'RealizedVolatility', 'REVS60', 'REVS120', 'REVS250', 'REVS750', 'REVS5m20', 'REVS5m60', 'REVS5Indu1', 'REVS20Indu1',
    'Volumn1M', 'Volumn3M', 'Price1M', 'Price3M', 'Price1Y', 'Rank1M', 'CashDividendCover', 'DividendCover',
    'DividendPaidRatio', 'RetainedEarningRatio', 'CashEquivalentPS', 'DividendPS', 'EPSTTM', 'NetAssetPS', 'TORPS',
    'TORPSLatest', 'OperatingRevenuePS', 'OperatingRevenuePSLatest', 'OperatingProfitPS', 'OperatingProfitPSLatest',
    'CapitalSurplusFundPS', 'SurplusReserveFundPS','UndividedProfitPS', 'RetainedEarningsPS', 'OperCashFlowPS',
    'CashFlowPS', 'NetNonOIToTP', 'NetNonOIToTPLatest', 'PeriodCostsRate', 'InterestCover', 'NetProfitGrowRate3Y',
    'NetProfitGrowRate5Y', 'OperatingRevenueGrowRate3Y', 'OperatingRevenueGrowRate5Y', 'NetCashFlowGrowRate',
    'NetProfitCashCover', 'OperCashInToAsset', 'CashConversionCycle', 'OperatingCycle', 'PEG3Y', 'PEG5Y', 'PEIndu',
    'PBIndu', 'PSIndu', 'PCFIndu', 'PEHist20', 'PEHist60', 'PEHist120', 'PEHist250', 'StaticPE', 'ForwardPE',
    'EnterpriseFCFPS', 'ShareholderFCFPS', 'ROEDiluted', 'ROEAvg', 'ROEWeighted', 'ROECut', 'ROECutWeighted',
    'ROIC', 'ROAEBIT', 'ROAEBITTTM', 'OperatingNIToTP', 'OperatingNIToTPLatest', 'InvestRAssociatesToTP', 'InvestRAssociatesToTPLatest',
    'NPCutToNP', 'SuperQuickRatio', 'TSEPToInterestBearDebt', 'DebtTangibleEquityRatio', 'TangibleAToInteBearDebt',
    'TangibleAToNetDebt', 'NOCFToTLiability', 'NOCFToInterestBearDebt', 'NOCFToNetDebt', 'TSEPToTotalCapital',
    'InteBearDebtToTotalCapital', 'NPParentCompanyCutYOY', 'SalesServiceCashToORLatest', 'CashRateOfSalesLatest',
    'NOCFToOperatingNILatest', 'TotalAssets', 'MktValue','NegMktValue', 'TEAP', 'NIAP', 'TotalFixedAssets',
    'IntFreeCL', 'IntFreeNCL', 'IntCL', 'IntDebt', 'NetDebt','NetTangibleAssets', 'WorkingCapital', 'NetWorkingCapital',
    'TotalPaidinCapital', 'RetainedEarnings', 'OperateNetIncome', 'ValueChgProfit', 'NetIntExpense', 'EBIT',
    'EBITDA', 'EBIAT', 'NRProfitLoss', 'NIAPCut', 'FCFF', 'FCFE', 'DA','TRevenueTTM', 'TCostTTM','RevenueTTM',
    'CostTTM', 'GrossProfitTTM', 'SalesExpenseTTM', 'AdminExpenseTTM', 'FinanExpenseTTM', 'AssetImpairLossTTM',
    'NPFromOperatingTTM', 'NPFromValueChgTTM', 'OperateProfitTTM', 'NonOperatingNPTTM', 'TProfitTTM', 'NetProfitTTM',
    'NetProfitAPTTM', 'SaleServiceRenderCashTTM', 'NetOperateCFTTM', 'NetInvestCFTTM', 'NetFinanceCFTTM', 'GrossProfit',
    'Beta252', 'RSTR504', 'EPIBS', 'CETOP', 'DASTD', 'CmraCNE5', 'HsigmaCNE5', 'SGRO', 'EgibsLong', 'STOM', 'STOQ', 'STOA', 'NLSIZE']

alpha_features = [
    'alpha_1', 'alpha_2', 'alpha_3', 'alpha_4', 'alpha_5', 'alpha_6', 'alpha_7', 'alpha_8', 'alpha_9', 'alpha_10',
    'alpha_11', 'alpha_12', 'alpha_13', 'alpha_14', 'alpha_15', 'alpha_16', 'alpha_17', 'alpha_18', 'alpha_19', 'alpha_20',
    'alpha_21', 'alpha_22', 'alpha_23', 'alpha_24', 'alpha_25', 'alpha_26', 'alpha_27', 'alpha_28', 'alpha_29', 'alpha_30',
    'alpha_31', 'alpha_32', 'alpha_33', 'alpha_34', 'alpha_35', 'alpha_36', 'alpha_37', 'alpha_38', 'alpha_39', 'alpha_40',
    'alpha_41', 'alpha_42', 'alpha_43', 'alpha_44', 'alpha_45', 'alpha_46', 'alpha_47', 'alpha_48', 'alpha_49', 'alpha_50',
    'alpha_51', 'alpha_52', 'alpha_53', 'alpha_54', 'alpha_55', 'alpha_56', 'alpha_57', 'alpha_58', 'alpha_59', 'alpha_60',
    'alpha_61', 'alpha_62', 'alpha_63', 'alpha_64', 'alpha_65', 'alpha_66', 'alpha_67', 'alpha_68', 'alpha_69', 'alpha_70',
    'alpha_71', 'alpha_72', 'alpha_73', 'alpha_74', 'alpha_75', 'alpha_76', 'alpha_77', 'alpha_78', 'alpha_79', 'alpha_80',
    'alpha_81', 'alpha_82', 'alpha_83', 'alpha_84', 'alpha_85', 'alpha_86', 'alpha_87', 'alpha_88', 'alpha_89', 'alpha_90',
    'alpha_91', 'alpha_92', 'alpha_93', 'alpha_94', 'alpha_95', 'alpha_96', 'alpha_97', 'alpha_98', 'alpha_99', 'alpha_100',
    'alpha_101', 'alpha_102', 'alpha_103', 'alpha_104', 'alpha_105', 'alpha_106', 'alpha_107', 'alpha_108', 'alpha_109', 'alpha_110',
    'alpha_111', 'alpha_112', 'alpha_113', 'alpha_114', 'alpha_115', 'alpha_116', 'alpha_117', 'alpha_118', 'alpha_119', 'alpha_120',
    'alpha_121', 'alpha_122', 'alpha_123', 'alpha_124', 'alpha_125', 'alpha_126', 'alpha_127', 'alpha_128', 'alpha_129', 'alpha_130',
    'alpha_131', 'alpha_132', 'alpha_133', 'alpha_134', 'alpha_135', 'alpha_136', 'alpha_137', 'alpha_138', 'alpha_139', 'alpha_140',
    'alpha_141', 'alpha_142', 'alpha_143', 'alpha_144', 'alpha_145', 'alpha_146', 'alpha_147', 'alpha_148', 'alpha_149', 'alpha_150',
    'alpha_151', 'alpha_152', 'alpha_153', 'alpha_154', 'alpha_155', 'alpha_156', 'alpha_157', 'alpha_158', 'alpha_159', 'alpha_160',
    'alpha_171', 'alpha_172', 'alpha_173', 'alpha_174', 'alpha_175', 'alpha_176', 'alpha_177', 'alpha_178', 'alpha_179', 'alpha_180',
    'alpha_181', 'alpha_182', 'alpha_183', 'alpha_184', 'alpha_185', 'alpha_186', 'alpha_187', 'alpha_188', 'alpha_189', 'alpha_190',
    'alpha_191'
]