# -*- coding: utf-8 -*-
from sqlalchemy import BigInteger, Column, DateTime, Float, Index, Integer, String, Text, Boolean, text, JSON,TIMESTAMP
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()
metadata = Base.metadata

class VisionSWIndustry(Base):
    __tablename__ = 'sw_industry'
    id = Column(String(128), primary_key=True, nullable=False)
    isymbol = Column(String(24), primary_key=True, nullable=False)
    trade_date = Column(DateTime, primary_key=True, nullable=False)
    iname = Column(String(128))
    symbol = Column(String(32))
    sname = Column(String(128))
    weighing = Column(Float(53))
    
    
class VisionIndex(Base):
    __tablename__ = 'index'
    id = Column(String(128), primary_key=True, nullable=False)
    isymbol = Column(String(24), primary_key=True, nullable=False)
    trade_date = Column(DateTime, primary_key=True, nullable=False)
    iname = Column(String(128))
    symbol = Column(String(32))
    sname = Column(String(128))
    weighing = Column(Float(53))
    
class Market5MinBar(Base):
    __tablename__ = 'market_bar_5mins'
    trade_date = Column(TIMESTAMP, primary_key=True, nullable=False)
    code = Column(Integer, primary_key=True, nullable=False)
    bar_time = Column(String)
    close_price = Column(Float(53))
    high_price = Column(Float(53))
    low_price = Column(Float(53))
    open_price = Column(Float(53))
    total_value = Column(Float(53))
    total_volume = Column(Float(53))
    vwap = Column(Float(53))
    twap = Column(Float(53))
    accumadjfactor = Column(Float(53))
    
class Experimental(Base):
    __tablename__ = 'experimental'
    trade_date = Column(DateTime, primary_key=True, nullable=False)
    code = Column(String, primary_key=True, nullable=False)
    ROEAfterNonRecurring = Column(Float(53))
    CHV = Column(Float(53))
    DROE = Column(Float(53))
    IVR = Column(Float(53))
    EPAfterNonRecurring = Column(Float(53))
    DROEAfterNonRecurring = Column(Float(53))
    CFinc1 = Column(Float(53))
    Revenue = Column(Float(53))
    DRevenue = Column(Float(53))

class Market(Base):
    __tablename__ = 'market'
    __table_args__ = (
        Index('market_idx', 'trade_date', 'code', unique=True),
    )

    trade_date = Column(DateTime, primary_key=True, nullable=False)
    code = Column(String, primary_key=True, nullable=False)
    secShortName = Column(String(10))
    exchangeCD = Column(String(4))
    preClosePrice = Column(Float(53))
    actPreClosePrice = Column(Float(53))
    openPrice = Column(Float(53))
    highestPrice = Column(Float(53))
    lowestPrice = Column(Float(53))
    closePrice = Column(Float(53))
    turnoverVol = Column(BigInteger)
    turnoverValue = Column(Float(53))
    dealAmount = Column(BigInteger)
    turnoverRate = Column(Float(53))
    accumAdjFactor = Column(Float(53))
    negMarketValue = Column(Float(53))
    marketValue = Column(Float(53))
    chgPct = Column(Float(53))
    PE = Column(Float(53))
    PE1 = Column(Float(53))
    PB = Column(Float(53))
    isOpen = Column(Integer)
    vwap = Column(Float(53))
    
class RiskExposure(Base):
    __tablename__ = 'risk_exposure'
    trade_date =  Column(DateTime, primary_key=True, nullable=False)
    code =  Column(String, primary_key=True, nullable=False)
    BETA = Column(Float(53))
    MOMENTUM = Column(Float(53))
    SIZE = Column(Float(53))
    EARNYILD = Column(Float(53))
    RESVOL = Column(Float(53))
    GROWTH = Column(Float(53))
    BTOP = Column(Float(53))
    LEVERAGE = Column(Float(53))
    LIQUIDTY = Column(Float(53))
    SIZENL = Column(Float(53))
    Bank = Column(Float(53))
    RealEstate = Column(Float(53))
    Health = Column(Float(53))
    Transportation = Column(Float(53))
    Mining = Column(Float(53))
    NonFerMetal = Column(Float(53))
    HouseApp = Column(Float(53))
    LeiService = Column(Float(53))
    MachiEquip = Column(Float(53))
    BuildDeco = Column(Float(53))
    CommeTrade = Column(Float(53))
    CONMAT = Column(Float(53))
    Auto = Column(Float(53))
    Textile = Column(Float(53))
    FoodBever = Column(Float(53))
    Electronics = Column(Float(53))
    Computer = Column(Float(53))
    LightIndus = Column(Float(53))
    Utilities = Column(Float(53))
    Telecom = Column(Float(53))
    AgriForest = Column(Float(53))
    CHEM = Column(Float(53))
    Media = Column(Float(53))
    IronSteel = Column(Float(53))
    NonBankFinan = Column(Float(53))
    ELECEQP = Column(Float(53))
    AERODEF = Column(Float(53))
    Conglomerates = Column(Float(53))
    COUNTRY = Column(Float(53))
    updateTime = Column(DateTime)

class RiskReturn(Base):
    __tablename__ = 'risk_return'
    trade_date =  Column(DateTime, primary_key=True, nullable=False)
    BETA = Column(Float(53))
    MOMENTUM = Column(Float(53))
    SIZE = Column(Float(53))
    EARNYILD = Column(Float(53))
    RESVOL = Column(Float(53))
    GROWTH = Column(Float(53))
    BTOP = Column(Float(53))
    LEVERAGE = Column(Float(53))
    LIQUIDTY = Column(Float(53))
    SIZENL = Column(Float(53))
    Bank = Column(Float(53))
    RealEstate = Column(Float(53))
    Health = Column(Float(53))
    Transportation = Column(Float(53))
    Mining = Column(Float(53))
    NonFerMetal = Column(Float(53))
    HouseApp = Column(Float(53))
    LeiService = Column(Float(53))
    MachiEquip = Column(Float(53))
    BuildDeco = Column(Float(53))
    CommeTrade = Column(Float(53))
    CONMAT = Column(Float(53))
    Auto = Column(Float(53))
    Textile = Column(Float(53))
    FoodBever = Column(Float(53))
    Electronics = Column(Float(53))
    Computer = Column(Float(53))
    LightIndus = Column(Float(53))
    Utilities = Column(Float(53))
    Telecom = Column(Float(53))
    AgriForest = Column(Float(53))
    CHEM = Column(Float(53))
    Media = Column(Float(53))
    IronSteel = Column(Float(53))
    NonBankFinan = Column(Float(53))
    ELECEQP = Column(Float(53))
    AERODEF = Column(Float(53))
    Conglomerates = Column(Float(53))
    COUNTRY = Column(Float(53))
    updateTime = Column(DateTime)

class Min5DailyHighFrequency(Base):
    __tablename__ = '5min_daily_high_frequency'
    trade_date = Column(DateTime, primary_key=True, nullable=False)
    code = Column(Integer, primary_key=True, nullable=False)
    
    flow_in_ratio1_20 = Column(Float(53))
    improved_reversal_20 = Column(Float(53))
    trend_strength_20 = Column(Float(53))
    volume_price_corr_20 = Column(Float(53))
    volume_ratio_1000 = Column(Float(53))
    volume_ratio_1030 = Column(Float(53))
    volume_ratio_1100 = Column(Float(53))
    volume_ratio_1130 = Column(Float(53))
    volume_ratio_1330 = Column(Float(53))
    volume_ratio_1400 = Column(Float(53))
    volume_ratio_1430 = Column(Float(53))
    volume_ratio_1500 = Column(Float(53))

class Alpha191(Base):
    __tablename__ = 'alpha191'
    trade_date = Column(DateTime, primary_key=True, nullable=False)
    code = Column(Integer, primary_key=True, nullable=False)
    alpha_1 = Column(Float(53))
    alpha_2 = Column(Float(53))
    alpha_3 = Column(Float(53))
    alpha_4 = Column(Float(53))
    alpha_5 = Column(Float(53))
    alpha_6 = Column(Float(53))
    alpha_7 = Column(Float(53))
    alpha_8 = Column(Float(53))
    alpha_9 = Column(Float(53))
    alpha_10 = Column(Float(53))
    alpha_11 = Column(Float(53))
    alpha_12 = Column(Float(53))
    alpha_13 = Column(Float(53))
    alpha_14 = Column(Float(53))
    alpha_15 = Column(Float(53))
    alpha_16 = Column(Float(53))
    alpha_17 = Column(Float(53))
    alpha_18 = Column(Float(53))
    alpha_19 = Column(Float(53))
    alpha_20 = Column(Float(53))
    alpha_21 = Column(Float(53))
    alpha_22 = Column(Float(53))
    alpha_23 = Column(Float(53))
    alpha_24 = Column(Float(53))
    alpha_25 = Column(Float(53))
    alpha_26 = Column(Float(53))
    alpha_27 = Column(Float(53))
    alpha_28 = Column(Float(53))
    alpha_29 = Column(Float(53))
    alpha_30 = Column(Float(53))
    alpha_31 = Column(Float(53))
    alpha_32 = Column(Float(53))
    alpha_33 = Column(Float(53))
    alpha_34 = Column(Float(53))
    alpha_35 = Column(Float(53))
    alpha_36 = Column(Float(53))
    alpha_37 = Column(Float(53))
    alpha_38 = Column(Float(53))
    alpha_39 = Column(Float(53))
    alpha_40 = Column(Float(53))
    alpha_41 = Column(Float(53))
    alpha_42 = Column(Float(53))
    alpha_43 = Column(Float(53))
    alpha_44 = Column(Float(53))
    alpha_45 = Column(Float(53))
    alpha_46 = Column(Float(53))
    alpha_47 = Column(Float(53))
    alpha_48 = Column(Float(53))
    alpha_49 = Column(Float(53))
    alpha_50 = Column(Float(53))
    alpha_51 = Column(Float(53))
    alpha_52 = Column(Float(53))
    alpha_53 = Column(Float(53))
    alpha_54 = Column(Float(53))
    alpha_55 = Column(Float(53))
    alpha_56 = Column(Float(53))
    alpha_57 = Column(Float(53))
    alpha_58 = Column(Float(53))
    alpha_59 = Column(Float(53))
    alpha_60 = Column(Float(53))
    alpha_61 = Column(Float(53))
    alpha_62 = Column(Float(53))
    alpha_63 = Column(Float(53))
    alpha_64 = Column(Float(53))
    alpha_65 = Column(Float(53))
    alpha_66 = Column(Float(53))
    alpha_67 = Column(Float(53))
    alpha_68 = Column(Float(53))
    alpha_69 = Column(Float(53))
    alpha_70 = Column(Float(53))