# -*- coding: utf-8 -*-
from sqlalchemy import BigInteger, Column, DateTime, Float, Index, Integer, String, Text, Boolean, text, JSON,TIMESTAMP
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()
metadata = Base.metadata

class VisionSWIndustry(Base):
    __tablename__ = 'sw_industry'
    id = Column(String(128), primary_key=True, nullable=False)
    isymbol = Column(String(24), primary_key=True, nullable=False)
    trade_date = Column(DateTime, primary_key=True, nullable=False)
    iname = Column(String(128))
    symbol = Column(String(32))
    sname = Column(String(128))
    weighing = Column(Float(53))
    
    
class VisionIndex(Base):
    __tablename__ = 'index'
    id = Column(String(128), primary_key=True, nullable=False)
    isymbol = Column(String(24), primary_key=True, nullable=False)
    trade_date = Column(DateTime, primary_key=True, nullable=False)
    iname = Column(String(128))
    symbol = Column(String(32))
    sname = Column(String(128))
    weighing = Column(Float(53))
    
class Market5MinBar(Base):
    __tablename__ = 'market_bar_5mins'
    trade_date = Column(TIMESTAMP, primary_key=True, nullable=False)
    code = Column(Integer, primary_key=True, nullable=False)
    bar_time = Column(String)
    close_price = Column(Float(53))
    high_price = Column(Float(53))
    low_price = Column(Float(53))
    open_price = Column(Float(53))
    total_value = Column(Float(53))
    total_volume = Column(Float(53))
    vwap = Column(Float(53))
    twap = Column(Float(53))
    accumadjfactor = Column(Float(53))
    
class Experimental(Base):
    __tablename__ = 'experimental'
    trade_date = Column(DateTime, primary_key=True, nullable=False)
    code = Column(String, primary_key=True, nullable=False)
    ROEAfterNonRecurring = Column(Float(53))
    CHV = Column(Float(53))
    DROE = Column(Float(53))
    IVR = Column(Float(53))
    EPAfterNonRecurring = Column(Float(53))
    DROEAfterNonRecurring = Column(Float(53))
    CFinc1 = Column(Float(53))
    Revenue = Column(Float(53))
    DRevenue = Column(Float(53))

class Market(Base):
    __tablename__ = 'market'
    __table_args__ = (
        Index('market_idx', 'trade_date', 'code', unique=True),
    )

    trade_date = Column(DateTime, primary_key=True, nullable=False)
    code = Column(String, primary_key=True, nullable=False)
    secShortName = Column(String(10))
    exchangeCD = Column(String(4))
    preClosePrice = Column(Float(53))
    actPreClosePrice = Column(Float(53))
    openPrice = Column(Float(53))
    highestPrice = Column(Float(53))
    lowestPrice = Column(Float(53))
    closePrice = Column(Float(53))
    turnoverVol = Column(BigInteger)
    turnoverValue = Column(Float(53))
    dealAmount = Column(BigInteger)
    turnoverRate = Column(Float(53))
    accumAdjFactor = Column(Float(53))
    negMarketValue = Column(Float(53))
    marketValue = Column(Float(53))
    chgPct = Column(Float(53))
    PE = Column(Float(53))
    PE1 = Column(Float(53))
    PB = Column(Float(53))
    isOpen = Column(Integer)
    vwap = Column(Float(53))
    
class RiskExposure(Base):
    __tablename__ = 'risk_exposure'
    trade_date =  Column(DateTime, primary_key=True, nullable=False)
    code =  Column(String, primary_key=True, nullable=False)
    BETA = Column(Float(53))
    MOMENTUM = Column(Float(53))
    SIZE = Column(Float(53))
    EARNYILD = Column(Float(53))
    RESVOL = Column(Float(53))
    GROWTH = Column(Float(53))
    BTOP = Column(Float(53))
    LEVERAGE = Column(Float(53))
    LIQUIDTY = Column(Float(53))
    SIZENL = Column(Float(53))
    Bank = Column(Float(53))
    RealEstate = Column(Float(53))
    Health = Column(Float(53))
    Transportation = Column(Float(53))
    Mining = Column(Float(53))
    NonFerMetal = Column(Float(53))
    HouseApp = Column(Float(53))
    LeiService = Column(Float(53))
    MachiEquip = Column(Float(53))
    BuildDeco = Column(Float(53))
    CommeTrade = Column(Float(53))
    CONMAT = Column(Float(53))
    Auto = Column(Float(53))
    Textile = Column(Float(53))
    FoodBever = Column(Float(53))
    Electronics = Column(Float(53))
    Computer = Column(Float(53))
    LightIndus = Column(Float(53))
    Utilities = Column(Float(53))
    Telecom = Column(Float(53))
    AgriForest = Column(Float(53))
    CHEM = Column(Float(53))
    Media = Column(Float(53))
    IronSteel = Column(Float(53))
    NonBankFinan = Column(Float(53))
    ELECEQP = Column(Float(53))
    AERODEF = Column(Float(53))
    Conglomerates = Column(Float(53))
    COUNTRY = Column(Float(53))
    updateTime = Column(DateTime)

class RiskReturn(Base):
    __tablename__ = 'risk_return'
    trade_date =  Column(DateTime, primary_key=True, nullable=False)
    BETA = Column(Float(53))
    MOMENTUM = Column(Float(53))
    SIZE = Column(Float(53))
    EARNYILD = Column(Float(53))
    RESVOL = Column(Float(53))
    GROWTH = Column(Float(53))
    BTOP = Column(Float(53))
    LEVERAGE = Column(Float(53))
    LIQUIDTY = Column(Float(53))
    SIZENL = Column(Float(53))
    Bank = Column(Float(53))
    RealEstate = Column(Float(53))
    Health = Column(Float(53))
    Transportation = Column(Float(53))
    Mining = Column(Float(53))
    NonFerMetal = Column(Float(53))
    HouseApp = Column(Float(53))
    LeiService = Column(Float(53))
    MachiEquip = Column(Float(53))
    BuildDeco = Column(Float(53))
    CommeTrade = Column(Float(53))
    CONMAT = Column(Float(53))
    Auto = Column(Float(53))
    Textile = Column(Float(53))
    FoodBever = Column(Float(53))
    Electronics = Column(Float(53))
    Computer = Column(Float(53))
    LightIndus = Column(Float(53))
    Utilities = Column(Float(53))
    Telecom = Column(Float(53))
    AgriForest = Column(Float(53))
    CHEM = Column(Float(53))
    Media = Column(Float(53))
    IronSteel = Column(Float(53))
    NonBankFinan = Column(Float(53))
    ELECEQP = Column(Float(53))
    AERODEF = Column(Float(53))
    Conglomerates = Column(Float(53))
    COUNTRY = Column(Float(53))
    updateTime = Column(DateTime)

class Min5DailyHighFrequency(Base):
    __tablename__ = '5min_daily_high_frequency'
    trade_date = Column(DateTime, primary_key=True, nullable=False)
    code = Column(Integer, primary_key=True, nullable=False)
    
    flow_in_ratio1_20 = Column(Float(53))
    improved_reversal_20 = Column(Float(53))
    trend_strength_20 = Column(Float(53))
    volume_price_corr_20 = Column(Float(53))
    volume_ratio_1000 = Column(Float(53))
    volume_ratio_1030 = Column(Float(53))
    volume_ratio_1100 = Column(Float(53))
    volume_ratio_1130 = Column(Float(53))
    volume_ratio_1330 = Column(Float(53))
    volume_ratio_1400 = Column(Float(53))
    volume_ratio_1430 = Column(Float(53))
    volume_ratio_1500 = Column(Float(53))

class Alpha191(Base):
    __tablename__ = 'alpha191'
    trade_date = Column(DateTime, primary_key=True, nullable=False)
    code = Column(Integer, primary_key=True, nullable=False)
    alpha_1 = Column(Float(53))
    alpha_2 = Column(Float(53))
    alpha_3 = Column(Float(53))
    alpha_4 = Column(Float(53))
    alpha_5 = Column(Float(53))
    alpha_6 = Column(Float(53))
    alpha_7 = Column(Float(53))
    alpha_8 = Column(Float(53))
    alpha_9 = Column(Float(53))
    alpha_10 = Column(Float(53))
    alpha_11 = Column(Float(53))
    alpha_12 = Column(Float(53))
    alpha_13 = Column(Float(53))
    alpha_14 = Column(Float(53))
    alpha_15 = Column(Float(53))
    alpha_16 = Column(Float(53))
    alpha_17 = Column(Float(53))
    alpha_18 = Column(Float(53))
    alpha_19 = Column(Float(53))
    alpha_20 = Column(Float(53))
    alpha_21 = Column(Float(53))
    alpha_22 = Column(Float(53))
    alpha_23 = Column(Float(53))
    alpha_24 = Column(Float(53))
    alpha_25 = Column(Float(53))
    alpha_26 = Column(Float(53))
    alpha_27 = Column(Float(53))
    alpha_28 = Column(Float(53))
    alpha_29 = Column(Float(53))
    alpha_30 = Column(Float(53))
    alpha_31 = Column(Float(53))
    alpha_32 = Column(Float(53))
    alpha_33 = Column(Float(53))
    alpha_34 = Column(Float(53))
    alpha_35 = Column(Float(53))
    alpha_36 = Column(Float(53))
    alpha_37 = Column(Float(53))
    alpha_38 = Column(Float(53))
    alpha_39 = Column(Float(53))
    alpha_40 = Column(Float(53))
    alpha_41 = Column(Float(53))
    alpha_42 = Column(Float(53))
    alpha_43 = Column(Float(53))
    alpha_44 = Column(Float(53))
    alpha_45 = Column(Float(53))
    alpha_46 = Column(Float(53))
    alpha_47 = Column(Float(53))
    alpha_48 = Column(Float(53))
    alpha_49 = Column(Float(53))
    alpha_50 = Column(Float(53))
    alpha_51 = Column(Float(53))
    alpha_52 = Column(Float(53))
    alpha_53 = Column(Float(53))
    alpha_54 = Column(Float(53))
    alpha_55 = Column(Float(53))
    alpha_56 = Column(Float(53))
    alpha_57 = Column(Float(53))
    alpha_58 = Column(Float(53))
    alpha_59 = Column(Float(53))
    alpha_60 = Column(Float(53))
    alpha_61 = Column(Float(53))
    alpha_62 = Column(Float(53))
    alpha_63 = Column(Float(53))
    alpha_64 = Column(Float(53))
    alpha_65 = Column(Float(53))
    alpha_66 = Column(Float(53))
    alpha_67 = Column(Float(53))
    alpha_68 = Column(Float(53))
    alpha_69 = Column(Float(53))
    alpha_70 = Column(Float(53))
    alpha_71 = Column(Float(53))
    alpha_72 = Column(Float(53))
    alpha_73 = Column(Float(53))
    alpha_74 = Column(Float(53))
    alpha_75 = Column(Float(53))
    alpha_76 = Column(Float(53))
    alpha_77 = Column(Float(53))
    alpha_78 = Column(Float(53))
    alpha_79 = Column(Float(53))
    alpha_80 = Column(Float(53))
    alpha_81 = Column(Float(53))
    alpha_82 = Column(Float(53))
    alpha_83 = Column(Float(53))
    alpha_84 = Column(Float(53))
    alpha_85 = Column(Float(53))
    alpha_86 = Column(Float(53))
    alpha_87 = Column(Float(53))
    alpha_88 = Column(Float(53))
    alpha_89 = Column(Float(53))
    alpha_90 = Column(Float(53))
    alpha_91 = Column(Float(53))
    alpha_92 = Column(Float(53))
    alpha_93 = Column(Float(53))
    alpha_94 = Column(Float(53))
    alpha_95 = Column(Float(53))
    alpha_96 = Column(Float(53))
    alpha_97 = Column(Float(53))
    alpha_98 = Column(Float(53))
    alpha_99 = Column(Float(53))
    alpha_100 = Column(Float(53))
    alpha_101 = Column(Float(53))
    alpha_102 = Column(Float(53))
    alpha_103 = Column(Float(53))
    alpha_104 = Column(Float(53))
    alpha_105 = Column(Float(53))
    alpha_106 = Column(Float(53))
    alpha_107 = Column(Float(53))
    alpha_108 = Column(Float(53))
    alpha_109 = Column(Float(53))
    alpha_110 = Column(Float(53))
    alpha_111 = Column(Float(53))
    alpha_112 = Column(Float(53))
    alpha_113 = Column(Float(53))
    alpha_114 = Column(Float(53))
    alpha_115 = Column(Float(53))
    alpha_116 = Column(Float(53))
    alpha_117 = Column(Float(53))
    alpha_118 = Column(Float(53))
    alpha_119 = Column(Float(53))
    alpha_120 = Column(Float(53))
    alpha_121 = Column(Float(53))
    alpha_122 = Column(Float(53))
    alpha_123 = Column(Float(53))
    alpha_124 = Column(Float(53))
    alpha_125 = Column(Float(53))
    alpha_126 = Column(Float(53))
    alpha_127 = Column(Float(53))
    alpha_128 = Column(Float(53))
    alpha_129 = Column(Float(53))
    alpha_130 = Column(Float(53))
    alpha_131 = Column(Float(53))
    alpha_132 = Column(Float(53))
    alpha_133 = Column(Float(53))
    alpha_134 = Column(Float(53))
    alpha_135 = Column(Float(53))
    alpha_136 = Column(Float(53))
    alpha_137 = Column(Float(53))
    alpha_138 = Column(Float(53))
    alpha_139 = Column(Float(53))
    alpha_140 = Column(Float(53))
    alpha_141 = Column(Float(53))
    alpha_142 = Column(Float(53))
    alpha_143 = Column(Float(53))
    alpha_144 = Column(Float(53))
    alpha_145 = Column(Float(53))
    alpha_146 = Column(Float(53))
    alpha_147 = Column(Float(53))
    alpha_148 = Column(Float(53))
    alpha_149 = Column(Float(53))
    alpha_150 = Column(Float(53))
    alpha_151 = Column(Float(53))
    alpha_152 = Column(Float(53))
    alpha_153 = Column(Float(53))
    alpha_154 = Column(Float(53))
    alpha_155 = Column(Float(53))
    alpha_156 = Column(Float(53))
    alpha_157 = Column(Float(53))
    alpha_158 = Column(Float(53))
    alpha_159 = Column(Float(53))
    alpha_160 = Column(Float(53))
    alpha_161 = Column(Float(53))
    alpha_162 = Column(Float(53))
    alpha_163 = Column(Float(53))
    alpha_164 = Column(Float(53))
    alpha_165 = Column(Float(53))
    alpha_166 = Column(Float(53))
    alpha_167 = Column(Float(53))
    alpha_168 = Column(Float(53))
    alpha_169 = Column(Float(53))
    alpha_170 = Column(Float(53))
    alpha_171 = Column(Float(53))
    alpha_172 = Column(Float(53))
    alpha_173 = Column(Float(53))
    alpha_174 = Column(Float(53))
    alpha_175 = Column(Float(53))
    alpha_176 = Column(Float(53))
    alpha_177 = Column(Float(53))
    alpha_178 = Column(Float(53))
    alpha_179 = Column(Float(53))
    alpha_180 = Column(Float(53))
    alpha_181 = Column(Float(53))
    alpha_182 = Column(Float(53))
    alpha_183 = Column(Float(53))
    alpha_184 = Column(Float(53))
    alpha_185 = Column(Float(53))
    alpha_186 = Column(Float(53))
    alpha_187 = Column(Float(53))
    alpha_188 = Column(Float(53))
    alpha_189 = Column(Float(53))
    alpha_190 = Column(Float(53))
    alpha_191 = Column(Float(53))